
spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: ${DATABASE_URI}
    
    password: ${DATABASE_PASSWORD}
    username: ${DATABASE_USER}
    driverClassName: org.postgresql.Driver
    dbcp2:
      max-total: 20
    initialization-mode: never
# App:
hiProperties:
  app:
    jwtSecret: ${JWT_KEY}
    jwtExpirationMs: 86400000